# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
