# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 21, 22, 5, 829233, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
