# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20170820_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=0, verbose_name='date published'),
        ),
    ]
