# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 18:12
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20170820_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(default=0, verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default='static/images/default.png', upload_to=articles.models.get_upload_file_name),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
