# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20170905_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='default_title', max_length=100),
        ),
    ]
