# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='lazy', max_length=100),
        ),
    ]
