# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
